name: generate-site
on: [ push ]

jobs:
  gen-site:
    runs-on: ubuntu-latest

    name: Generate index and site assets
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install RPM tools
        run: sudo apt install -y rpm gpg createrepo-c dpkg-dev reprepro

      - name: Setup requirements
        run: pip install -r requirements.txt

      - name: Download packages
        run: python scripts/fetch-releases.py

      - name: Import GPG key
        id: gpg-import
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Sign RPMs
        shell: sh
        run: sh scripts/sign-rpms.sh ${{ steps.gpg-import.outputs.fingerprint }}

      - name: Create YUM repository
        shell: sh
        run: createrepo_c -v _site/rpm

      - name: Sign YUM repository
        shell: sh
        run: gpg --armor --detach-sign _site/rpm/repodata/repomd.xml

      - name: Create APT repository
        shell: sh
        run: sh -x scripts/generate-apt-repo.sh

      - name: Prepare assets
        run: |
          cp -aRv dragonfly.repo pgp-key.public dragonfly.sources _site/
          rm -rf _site/deb/conf

      - name: Generate Directory Listings
        run: python scripts/generate-index.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1

  deploy:
    needs: gen-site
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.0
